# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI1.ui'
#
# Created: Mon Feb 01 16:43:09 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 326)
        MainWindow.setAcceptDrops(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 161, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.CHP = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.CHP.setObjectName("CHP")
        self.verticalLayout.addWidget(self.CHP)
        self.boiler = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.boiler.setObjectName("boiler")
        self.verticalLayout.addWidget(self.boiler)
        self.thermalstorage = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.thermalstorage.setObjectName("thermalstorage")
        self.verticalLayout.addWidget(self.thermalstorage)
        self.solarthermal = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.solarthermal.setObjectName("solarthermal")
        self.verticalLayout.addWidget(self.solarthermal)
        self.electricheater = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.electricheater.setObjectName("electricheater")
        self.verticalLayout.addWidget(self.electricheater)
        self.photovoltaics = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.photovoltaics.setObjectName("photovoltaics")
        self.verticalLayout.addWidget(self.photovoltaics)
        self.electricstorage = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.electricstorage.setObjectName("electricstorage")
        self.verticalLayout.addWidget(self.electricstorage)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(200, 250, 159, 31))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.radioButton = QtGui.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(180, 220, 171, 16))
        self.radioButton.setObjectName("radioButton")
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(427, 30, 77, 154))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnOutputBrowse = QtGui.QPushButton(self.widget)
        self.btnOutputBrowse.setObjectName("btnOutputBrowse")
        self.verticalLayout_3.addWidget(self.btnOutputBrowse)
        self.btnWeathreBrowse = QtGui.QPushButton(self.widget)
        self.btnWeathreBrowse.setObjectName("btnWeathreBrowse")
        self.verticalLayout_3.addWidget(self.btnWeathreBrowse)
        self.btnHeatprofilesBrowse = QtGui.QPushButton(self.widget)
        self.btnHeatprofilesBrowse.setObjectName("btnHeatprofilesBrowse")
        self.verticalLayout_3.addWidget(self.btnHeatprofilesBrowse)
        self.btnElProfileBrowse = QtGui.QPushButton(self.widget)
        self.btnElProfileBrowse.setObjectName("btnElProfileBrowse")
        self.verticalLayout_3.addWidget(self.btnElProfileBrowse)
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(170, 10, 261, 201))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setContentsMargins(20, 20, 0, 20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtGui.QListWidget(self.widget1)
        self.listWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.listWidget.setAcceptDrops(True)
        self.listWidget.setAutoFillBackground(False)
        self.listWidget.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.listWidget_2 = QtGui.QListWidget(self.widget1)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_2.addWidget(self.listWidget_2)
        self.listWidget_3 = QtGui.QListWidget(self.widget1)
        self.listWidget_3.setObjectName("listWidget_3")
        self.verticalLayout_2.addWidget(self.listWidget_3)
        self.listWidget_4 = QtGui.QListWidget(self.widget1)
        self.listWidget_4.setObjectName("listWidget_4")
        self.verticalLayout_2.addWidget(self.listWidget_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 558, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.CHP, QtCore.SIGNAL("clicked(bool)"), self.CHP.setChecked)
        QtCore.QObject.connect(self.boiler, QtCore.SIGNAL("clicked(bool)"), self.boiler.update)
        QtCore.QObject.connect(self.electricheater, QtCore.SIGNAL("pressed()"), self.electricheater.update)
        QtCore.QObject.connect(self.electricstorage, QtCore.SIGNAL("pressed()"), self.electricstorage.update)
        QtCore.QObject.connect(self.photovoltaics, QtCore.SIGNAL("pressed()"), self.photovoltaics.update)
        QtCore.QObject.connect(self.solarthermal, QtCore.SIGNAL("pressed()"), self.solarthermal.update)
        QtCore.QObject.connect(self.thermalstorage, QtCore.SIGNAL("pressed()"), self.thermalstorage.update)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), self.buttonBox.update)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), self.buttonBox.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Choose technologies that can be present in the system:", None, QtGui.QApplication.UnicodeUTF8))
        self.CHP.setText(QtGui.QApplication.translate("MainWindow", "CHP", None, QtGui.QApplication.UnicodeUTF8))
        self.boiler.setText(QtGui.QApplication.translate("MainWindow", "Boiler", None, QtGui.QApplication.UnicodeUTF8))
        self.thermalstorage.setText(QtGui.QApplication.translate("MainWindow", "Thermal Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.solarthermal.setText(QtGui.QApplication.translate("MainWindow", "Solar Thermal", None, QtGui.QApplication.UnicodeUTF8))
        self.electricheater.setText(QtGui.QApplication.translate("MainWindow", "Electric Heater", None, QtGui.QApplication.UnicodeUTF8))
        self.photovoltaics.setText(QtGui.QApplication.translate("MainWindow", "Photovoltaics", None, QtGui.QApplication.UnicodeUTF8))
        self.electricstorage.setText(QtGui.QApplication.translate("MainWindow", "Electric Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "Hourly excels required?", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOutputBrowse.setText(QtGui.QApplication.translate("MainWindow", "Browse..", None, QtGui.QApplication.UnicodeUTF8))
        self.btnWeathreBrowse.setText(QtGui.QApplication.translate("MainWindow", "Browse..", None, QtGui.QApplication.UnicodeUTF8))
        self.btnHeatprofilesBrowse.setText(QtGui.QApplication.translate("MainWindow", "Browse..", None, QtGui.QApplication.UnicodeUTF8))
        self.btnElProfileBrowse.setText(QtGui.QApplication.translate("MainWindow", "Browse..", None, QtGui.QApplication.UnicodeUTF8))
