# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI1.ui'
#
# Created: Tue Feb 02 14:41:07 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_rtrtjrtj(object):
    def setupUi(self, rtrtjrtj):
        rtrtjrtj.setObjectName("rtrtjrtj")
        rtrtjrtj.resize(555, 389)
        rtrtjrtj.setAcceptDrops(True)
        rtrtjrtj.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(rtrtjrtj)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 161, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label1 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label1.setTextFormat(QtCore.Qt.RichText)
        self.label1.setWordWrap(True)
        self.label1.setObjectName("label1")
        self.verticalLayout.addWidget(self.label1)
        self.CHP1 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.CHP1.setObjectName("CHP1")
        self.verticalLayout.addWidget(self.CHP1)
        self.boiler1 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.boiler1.setObjectName("boiler1")
        self.verticalLayout.addWidget(self.boiler1)
        self.thermalstorage = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.thermalstorage.setObjectName("thermalstorage")
        self.verticalLayout.addWidget(self.thermalstorage)
        self.solarthermal = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.solarthermal.setObjectName("solarthermal")
        self.verticalLayout.addWidget(self.solarthermal)
        self.electricheater1 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.electricheater1.setObjectName("electricheater1")
        self.verticalLayout.addWidget(self.electricheater1)
        self.photovoltaics1 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.photovoltaics1.setObjectName("photovoltaics1")
        self.verticalLayout.addWidget(self.photovoltaics1)
        self.electricstorage1 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.electricstorage1.setObjectName("electricstorage1")
        self.verticalLayout.addWidget(self.electricstorage1)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(200, 250, 159, 31))
        self.buttonBox.setToolTip("")
        self.buttonBox.setStatusTip("")
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Discard|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.radioButton = QtGui.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(180, 220, 171, 16))
        self.radioButton.setObjectName("radioButton")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(427, 30, 77, 154))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnOutputBrowse = QtGui.QPushButton(self.layoutWidget)
        self.btnOutputBrowse.setObjectName("btnOutputBrowse")
        self.verticalLayout_3.addWidget(self.btnOutputBrowse)
        self.btnWeathreBrowse = QtGui.QPushButton(self.layoutWidget)
        self.btnWeathreBrowse.setObjectName("btnWeathreBrowse")
        self.verticalLayout_3.addWidget(self.btnWeathreBrowse)
        self.btnHeatprofilesBrowse = QtGui.QPushButton(self.layoutWidget)
        self.btnHeatprofilesBrowse.setObjectName("btnHeatprofilesBrowse")
        self.verticalLayout_3.addWidget(self.btnHeatprofilesBrowse)
        self.btnElProfileBrowse = QtGui.QPushButton(self.layoutWidget)
        self.btnElProfileBrowse.setObjectName("btnElProfileBrowse")
        self.verticalLayout_3.addWidget(self.btnElProfileBrowse)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(370, 280, 104, 71))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.layoutWidget1 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(210, 30, 211, 151))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.OutputFolderLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.OutputFolderLineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.OutputFolderLineEdit.setObjectName("OutputFolderLineEdit")
        self.verticalLayout_2.addWidget(self.OutputFolderLineEdit)
        self.WeatherDataLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.WeatherDataLineEdit.setObjectName("WeatherDataLineEdit")
        self.verticalLayout_2.addWidget(self.WeatherDataLineEdit)
        self.ElProfileLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.ElProfileLineEdit.setObjectName("ElProfileLineEdit")
        self.verticalLayout_2.addWidget(self.ElProfileLineEdit)
        self.HProfileLineEdit = QtGui.QLineEdit(self.layoutWidget1)
        self.HProfileLineEdit.setObjectName("HProfileLineEdit")
        self.verticalLayout_2.addWidget(self.HProfileLineEdit)
        rtrtjrtj.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(rtrtjrtj)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 21))
        self.menubar.setObjectName("menubar")
        rtrtjrtj.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(rtrtjrtj)
        self.statusbar.setObjectName("statusbar")
        rtrtjrtj.setStatusBar(self.statusbar)

        self.retranslateUi(rtrtjrtj)
        QtCore.QObject.connect(self.CHP1, QtCore.SIGNAL("clicked(bool)"), self.CHP1.setChecked)
        QtCore.QObject.connect(self.boiler1, QtCore.SIGNAL("clicked(bool)"), self.boiler1.update)
        QtCore.QObject.connect(self.electricheater1, QtCore.SIGNAL("pressed()"), self.electricheater1.update)
        QtCore.QObject.connect(self.electricstorage1, QtCore.SIGNAL("pressed()"), self.electricstorage1.update)
        QtCore.QObject.connect(self.photovoltaics1, QtCore.SIGNAL("pressed()"), self.photovoltaics1.update)
        QtCore.QObject.connect(self.solarthermal, QtCore.SIGNAL("pressed()"), self.solarthermal.update)
        QtCore.QObject.connect(self.thermalstorage, QtCore.SIGNAL("pressed()"), self.thermalstorage.update)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), self.buttonBox.update)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), self.buttonBox.close)
        QtCore.QObject.connect(self.btnOutputBrowse, QtCore.SIGNAL("clicked()"), self.btnOutputBrowse.click)
        QtCore.QMetaObject.connectSlotsByName(rtrtjrtj)

    def retranslateUi(self, rtrtjrtj):
        rtrtjrtj.setWindowTitle(QtGui.QApplication.translate("rtrtjrtj", "Welcome to the SGT UI", None, QtGui.QApplication.UnicodeUTF8))
        self.label1.setText(QtGui.QApplication.translate("rtrtjrtj", "Choose technologies that can be present in the system:", None, QtGui.QApplication.UnicodeUTF8))
        self.CHP1.setText(QtGui.QApplication.translate("rtrtjrtj", "CHP", None, QtGui.QApplication.UnicodeUTF8))
        self.boiler1.setText(QtGui.QApplication.translate("rtrtjrtj", "Boiler", None, QtGui.QApplication.UnicodeUTF8))
        self.thermalstorage.setText(QtGui.QApplication.translate("rtrtjrtj", "Thermal Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.solarthermal.setText(QtGui.QApplication.translate("rtrtjrtj", "Solar Thermal", None, QtGui.QApplication.UnicodeUTF8))
        self.electricheater1.setText(QtGui.QApplication.translate("rtrtjrtj", "Electric Heater", None, QtGui.QApplication.UnicodeUTF8))
        self.photovoltaics1.setText(QtGui.QApplication.translate("rtrtjrtj", "Photovoltaics", None, QtGui.QApplication.UnicodeUTF8))
        self.electricstorage1.setText(QtGui.QApplication.translate("rtrtjrtj", "Electric Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("rtrtjrtj", "Hourly excels required?", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOutputBrowse.setText(QtGui.QApplication.translate("rtrtjrtj", "Browse..", None, QtGui.QApplication.UnicodeUTF8))
        self.btnWeathreBrowse.setText(QtGui.QApplication.translate("rtrtjrtj", "Browse..", None, QtGui.QApplication.UnicodeUTF8))
        self.btnHeatprofilesBrowse.setText(QtGui.QApplication.translate("rtrtjrtj", "Browse..", None, QtGui.QApplication.UnicodeUTF8))
        self.btnElProfileBrowse.setText(QtGui.QApplication.translate("rtrtjrtj", "Browse..", None, QtGui.QApplication.UnicodeUTF8))
        self.OutputFolderLineEdit.setPlaceholderText(QtGui.QApplication.translate("rtrtjrtj", "Choose Output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.WeatherDataLineEdit.setPlaceholderText(QtGui.QApplication.translate("rtrtjrtj", "Choose TRY weather file", None, QtGui.QApplication.UnicodeUTF8))
        self.ElProfileLineEdit.setPlaceholderText(QtGui.QApplication.translate("rtrtjrtj", "Choose electrical profile", None, QtGui.QApplication.UnicodeUTF8))
        self.HProfileLineEdit.setPlaceholderText(QtGui.QApplication.translate("rtrtjrtj", "Choose heat profile", None, QtGui.QApplication.UnicodeUTF8))

