# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Mon Feb 01 14:59:26 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui


class UiMainWindow(object):

    def setup_gui(self, MainWindow):
        MainWindow.setObjectName("SGT!!!!!!!!!!!!!")
        MainWindow.resize(555, 389)
        MainWindow.setAcceptDrops(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 161, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label1 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label1.setTextFormat(QtCore.Qt.RichText)
        self.label1.setWordWrap(True)
        self.label1.setObjectName("label1")
        self.verticalLayout.addWidget(self.label1)
        self.check_box_chp = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.check_box_chp.setObjectName("check_box_chp")
        self.verticalLayout.addWidget(self.check_box_chp)
        self.check_box_boiler = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.check_box_boiler.setObjectName("check_box_boiler")
        self.verticalLayout.addWidget(self.check_box_boiler)
        self.check_box_thst = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.check_box_thst.setObjectName("thermalstorage")
        self.verticalLayout.addWidget(self.check_box_thst)
        self.check_box_solth = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.check_box_solth.setObjectName("solarthermal")
        self.verticalLayout.addWidget(self.check_box_solth)
        self.check_box_elhe = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.check_box_elhe.setObjectName("check_box_elhe")
        self.verticalLayout.addWidget(self.check_box_elhe)
        self.check_box_pv = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.check_box_pv.setObjectName("check_box_pv")
        self.verticalLayout.addWidget(self.check_box_pv)
        self.check_box_elst = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.check_box_elst.setObjectName("check_box_elst")
        self.verticalLayout.addWidget(self.check_box_elst)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(200, 250, 159, 31))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Ok|QtGui.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.rbtn_hourly_excels = QtGui.QRadioButton(self.centralwidget)
        self.rbtn_hourly_excels.setGeometry(QtCore.QRect(180, 220, 171, 16))
        self.rbtn_hourly_excels.setObjectName("rbtn_hourly_excels")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(427, 30, 77, 154))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_output_folder = QtGui.QPushButton(self.layoutWidget)
        self.btn_output_folder.setObjectName("btn_output_folder")
        self.verticalLayout_3.addWidget(self.btn_output_folder)
        self.btn_weather_file = QtGui.QPushButton(self.layoutWidget)
        self.btn_weather_file.setObjectName("btn_weather_file")
        self.verticalLayout_3.addWidget(self.btn_weather_file)
        self.btn_heat_profiles = QtGui.QPushButton(self.layoutWidget)
        self.btn_heat_profiles.setObjectName("btn_heat_profiles")
        self.verticalLayout_3.addWidget(self.btn_heat_profiles)
        self.btn_electrical_profiles = QtGui.QPushButton(self.layoutWidget)
        self.btn_electrical_profiles.setObjectName("btn_electrical_profiles")
        self.verticalLayout_3.addWidget(self.btn_electrical_profiles)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(210, 30, 211, 151))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_edit_output_folder = QtGui.QLineEdit(self.widget)
        self.line_edit_output_folder.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.line_edit_output_folder.setObjectName("line_edit_output_folder")
        self.verticalLayout_2.addWidget(self.line_edit_output_folder)
        self.line_edit_weather = QtGui.QLineEdit(self.widget)
        self.line_edit_weather.setObjectName("line_edit_weather")
        self.verticalLayout_2.addWidget(self.line_edit_weather)
        self.line_edit_heat_profiles = QtGui.QLineEdit(self.widget)
        self.line_edit_heat_profiles.setObjectName("line_edit_heat_profiles")
        self.verticalLayout_2.addWidget(self.line_edit_heat_profiles)
        self.line_edit_electrical_profiles = QtGui.QLineEdit(self.widget)
        self.line_edit_electrical_profiles.setObjectName("line_edit_electrical_profiles")
        self.verticalLayout_2.addWidget(self.line_edit_electrical_profiles)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.check_box_chp, QtCore.SIGNAL("clicked(bool)"), self.check_box_chp.setChecked)
        QtCore.QObject.connect(self.check_box_boiler, QtCore.SIGNAL("clicked(bool)"), self.check_box_boiler.setChecked)
        QtCore.QObject.connect(self.check_box_elhe, QtCore.SIGNAL("clicked(bool)"), self.check_box_elhe.setChecked)
        QtCore.QObject.connect(self.check_box_elst, QtCore.SIGNAL("clicked(bool)"), self.check_box_elst.setChecked)
        QtCore.QObject.connect(self.check_box_pv, QtCore.SIGNAL("clicked(bool)"), self.check_box_pv.setChecked)
        QtCore.QObject.connect(self.check_box_solth, QtCore.SIGNAL("clicked(bool)"), self.check_box_solth.setChecked)
        QtCore.QObject.connect(self.check_box_thst, QtCore.SIGNAL("clicked(bool)"), self.check_box_thst.setChecked)
        QtCore.QObject.connect(self.rbtn_hourly_excels, QtCore.SIGNAL("clicked(bool)"), self.rbtn_hourly_excels.setChecked)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Welcome to the SGT UI", None, QtGui.QApplication.UnicodeUTF8))
        self.label1.setText(QtGui.QApplication.translate("MainWindow", "Choose technologies that can be present in the system:", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_chp.setText(QtGui.QApplication.translate("MainWindow", "CHP", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_boiler.setText(QtGui.QApplication.translate("MainWindow", "Boiler", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_thst.setText(QtGui.QApplication.translate("MainWindow", "Thermal Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_solth.setText(QtGui.QApplication.translate("MainWindow", "Solar Thermal", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_elhe.setText(QtGui.QApplication.translate("MainWindow", "Electric Heater", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_pv.setText(QtGui.QApplication.translate("MainWindow", "Photovoltaics", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_elst.setText(QtGui.QApplication.translate("MainWindow", "Electric Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.rbtn_hourly_excels.setText(QtGui.QApplication.translate("MainWindow", "Hourly excels required?", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_output_folder.setText(QtGui.QApplication.translate("MainWindow", "Browse..", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_weather_file.setText(QtGui.QApplication.translate("MainWindow", "Browse..", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_heat_profiles.setText(QtGui.QApplication.translate("MainWindow", "Browse..", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_electrical_profiles.setText(QtGui.QApplication.translate("MainWindow", "Browse..", None, QtGui.QApplication.UnicodeUTF8))
