# -*- coding: utf-8 -*
from PySide import QtCore, QtGui

class UiMainWindow(object):
    def setup_gui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(887, 329)
        MainWindow.setAcceptDrops(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabTechnologies = QtGui.QWidget()
        self.tabTechnologies.setObjectName("tabTechnologies")
        self.verticalLayout = QtGui.QVBoxLayout(self.tabTechnologies)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label1 = QtGui.QLabel(self.tabTechnologies)
        self.label1.setTextFormat(QtCore.Qt.RichText)
        self.label1.setWordWrap(True)
        self.label1.setObjectName("label1")
        self.verticalLayout.addWidget(self.label1)
        self.check_box_chp = QtGui.QCheckBox(self.tabTechnologies)
        self.check_box_chp.setObjectName("check_box_chp")
        self.verticalLayout.addWidget(self.check_box_chp)
        self.check_box_boiler = QtGui.QCheckBox(self.tabTechnologies)
        self.check_box_boiler.setObjectName("check_box_boiler")
        self.verticalLayout.addWidget(self.check_box_boiler)
        self.check_box_thst = QtGui.QCheckBox(self.tabTechnologies)
        self.check_box_thst.setObjectName("check_box_thst")
        self.verticalLayout.addWidget(self.check_box_thst)
        self.check_box_solth = QtGui.QCheckBox(self.tabTechnologies)
        self.check_box_solth.setObjectName("check_box_solth")
        self.verticalLayout.addWidget(self.check_box_solth)
        self.check_box_elhe = QtGui.QCheckBox(self.tabTechnologies)
        self.check_box_elhe.setObjectName("check_box_elhe")
        self.verticalLayout.addWidget(self.check_box_elhe)
        self.check_box_pv = QtGui.QCheckBox(self.tabTechnologies)
        self.check_box_pv.setObjectName("check_box_pv")
        self.verticalLayout.addWidget(self.check_box_pv)
        self.check_box_elst = QtGui.QCheckBox(self.tabTechnologies)
        self.check_box_elst.setObjectName("check_box_elst")
        self.verticalLayout.addWidget(self.check_box_elst)
        self.tabWidget.addTab(self.tabTechnologies, "")
        self.tabFolders = QtGui.QWidget()
        self.tabFolders.setObjectName("tabFolders")
        self.gridLayout = QtGui.QGridLayout(self.tabFolders)
        self.gridLayout.setObjectName("gridLayout")
        self.OutputFolderLineEdit = QtGui.QLineEdit(self.tabFolders)
        self.OutputFolderLineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.OutputFolderLineEdit.setObjectName("OutputFolderLineEdit")
        self.OutputFolderLineEdit.setText("D:/aja-gmu/Simulation_Files/Output")

        self.gridLayout.addWidget(self.OutputFolderLineEdit, 0, 0, 1, 1)
        self.btnOutputBrowse = QtGui.QPushButton(self.tabFolders)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOutputBrowse.sizePolicy().hasHeightForWidth())
        self.btnOutputBrowse.setSizePolicy(sizePolicy)
        self.btnOutputBrowse.setDefault(False)
        self.btnOutputBrowse.setObjectName("btnOutputBrowse")
        self.gridLayout.addWidget(self.btnOutputBrowse, 0, 1, 1, 1)
        self.WeatherDataLineEdit = QtGui.QLineEdit(self.tabFolders)
        self.WeatherDataLineEdit.setObjectName("WeatherDataLineEdit")
        self.WeatherDataLineEdit.setText("D:/aja-gmu/Simulation_Files/Wetter_Bottrop_Modelica.csv")

        self.gridLayout.addWidget(self.WeatherDataLineEdit, 1, 0, 1, 1)
        self.btnWeathreBrowse = QtGui.QPushButton(self.tabFolders)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnWeathreBrowse.sizePolicy().hasHeightForWidth())
        self.btnWeathreBrowse.setSizePolicy(sizePolicy)
        self.btnWeathreBrowse.setObjectName("btnWeathreBrowse")
        self.gridLayout.addWidget(self.btnWeathreBrowse, 1, 1, 1, 1)
        self.ElProfileLineEdit = QtGui.QLineEdit(self.tabFolders)
        self.ElProfileLineEdit.setObjectName("ElProfileLineEdit")
        self.ElProfileLineEdit.setText("D:/aja-gmu/Simulation_Files/Heat profiles.xlsx")


        self.gridLayout.addWidget(self.ElProfileLineEdit, 2, 0, 1, 1)
        self.btnHeatprofilesBrowse = QtGui.QPushButton(self.tabFolders)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHeatprofilesBrowse.sizePolicy().hasHeightForWidth())
        self.btnHeatprofilesBrowse.setSizePolicy(sizePolicy)
        self.btnHeatprofilesBrowse.setObjectName("btnHeatprofilesBrowse")
        self.gridLayout.addWidget(self.btnHeatprofilesBrowse, 2, 1, 1, 1)
        self.HProfileLineEdit = QtGui.QLineEdit(self.tabFolders)
        self.HProfileLineEdit.setObjectName("HProfileLineEdit")
        self.HProfileLineEdit.setText("D:/aja-gmu/Simulation_Files/Heat profiles.xlsx")


        self.gridLayout.addWidget(self.HProfileLineEdit, 3, 0, 1, 1)
        self.btnElProfileBrowse = QtGui.QPushButton(self.tabFolders)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnElProfileBrowse.sizePolicy().hasHeightForWidth())
        self.btnElProfileBrowse.setSizePolicy(sizePolicy)
        self.btnElProfileBrowse.setObjectName("btnElProfileBrowse")
        self.gridLayout.addWidget(self.btnElProfileBrowse, 3, 1, 1, 1)
        self.rbtn_hourly_excels = QtGui.QRadioButton(self.tabFolders)
        self.rbtn_hourly_excels.setObjectName("rbtn_hourly_excels")
        self.gridLayout.addWidget(self.rbtn_hourly_excels, 4, 0, 1, 1)

        self.tabWidget.addTab(self.tabFolders, "")
        self.tabGDetails = QtGui.QWidget()
        self.tabGDetails.setObjectName("tabGDetails")
        self.gridLayout_2 = QtGui.QGridLayout(self.tabGDetails)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.labelElPrice = QtGui.QLabel(self.tabGDetails)
        self.labelElPrice.setObjectName("labelElPrice")
        self.gridLayout_2.addWidget(self.labelElPrice, 0, 0, 1, 1)

        self.lineEditElPrice = QtGui.QLineEdit(self.tabGDetails)
        self.lineEditElPrice.setObjectName("lineEditElPrice")
        self.lineEditElPrice.setText('0.26')
        self.gridLayout_2.addWidget(self.lineEditElPrice, 0, 1, 1, 1)

        self.labelElPriceUnit = QtGui.QLabel(self.tabGDetails)
        self.labelElPriceUnit.setObjectName("labelElPriceUnit")
        self.gridLayout_2.addWidget(self.labelElPriceUnit, 0, 2, 1, 1)

        self.labelGprice = QtGui.QLabel(self.tabGDetails)
        self.labelGprice.setObjectName("labelGprice")
        self.gridLayout_2.addWidget(self.labelGprice, 1, 0, 1, 1)

        self.lineEditGPrice = QtGui.QLineEdit(self.tabGDetails)
        self.lineEditGPrice.setObjectName("lineEditGPrice")
        self.gridLayout_2.addWidget(self.lineEditGPrice, 1, 1, 1, 1)
        self.lineEditGPrice.setText('0.067')

        self.labelGPriceUnit = QtGui.QLabel(self.tabGDetails)
        self.labelGPriceUnit.setObjectName("labelGPriceUnit")
        self.gridLayout_2.addWidget(self.labelGPriceUnit, 1, 2, 1, 1)

        self.tabWidget.addTab(self.tabGDetails, "")
        self.tabCHP = QtGui.QWidget()
        self.tabCHP.setObjectName("tabCHP")
        self.gridLayout_3 = QtGui.QGridLayout(self.tabCHP)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelCHPModelFix = QtGui.QLabel(self.tabCHP)
        self.labelCHPModelFix.setObjectName("labelCHPModelFix")
        self.gridLayout_3.addWidget(self.labelCHPModelFix, 7, 0, 1, 1)
        self.pushButtonAddCHP = QtGui.QPushButton(self.tabCHP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddCHP.sizePolicy().hasHeightForWidth())
        self.pushButtonAddCHP.setSizePolicy(sizePolicy)
        self.pushButtonAddCHP.setObjectName("pushButtonAddCHP")
        self.gridLayout_3.addWidget(self.pushButtonAddCHP, 5, 0, 1, 2)

        self.lineEditCHPFIT = QtGui.QLineEdit(self.tabCHP)
        self.lineEditCHPFIT.setObjectName("lineEditCHPFIT")
        self.lineEditCHPFIT.setText("0.10")
        self.gridLayout_3.addWidget(self.lineEditCHPFIT, 3, 1, 1, 1)

        self.labelCHPFITUnit = QtGui.QLabel(self.tabCHP)
        self.labelCHPFITUnit.setObjectName("labelCHPFITUnit")
        self.gridLayout_3.addWidget(self.labelCHPFITUnit, 3, 2, 1, 1)

        self.pushButtonAdvAnnuityCHP = QtGui.QPushButton(self.tabCHP)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdvAnnuityCHP.sizePolicy().hasHeightForWidth())
        self.pushButtonAdvAnnuityCHP.setSizePolicy(sizePolicy)
        self.pushButtonAdvAnnuityCHP.setObjectName("pushButtonAdvAnnuityCHP")
        self.gridLayout_3.addWidget(self.pushButtonAdvAnnuityCHP, 4, 0, 1, 2)
        self.radioButtonContCHP = QtGui.QRadioButton(self.tabCHP)
        self.radioButtonContCHP.setObjectName("radioButtonContCHP")
        self.gridLayout_3.addWidget(self.radioButtonContCHP, 2, 0, 1, 1)
        self.radioButtonONOFFCHP = QtGui.QRadioButton(self.tabCHP)
        self.radioButtonONOFFCHP.setObjectName("radioButtonONOFFCHP")
        self.gridLayout_3.addWidget(self.radioButtonONOFFCHP, 0, 0, 1, 1)
        self.lineEditCHPModelFix = QtGui.QLineEdit(self.tabCHP)
        self.lineEditCHPModelFix.setObjectName("lineEditCHPModelFix")
        self.gridLayout_3.addWidget(self.lineEditCHPModelFix, 7, 1, 1, 1)
        self.labelCHPFIT = QtGui.QLabel(self.tabCHP)
        self.labelCHPFIT.setObjectName("labelCHPFIT")
        self.gridLayout_3.addWidget(self.labelCHPFIT, 3, 0, 1, 1)
        self.radioButtonModCHP = QtGui.QRadioButton(self.tabCHP)
        self.radioButtonModCHP.setObjectName("radioButtonModCHP")
        self.gridLayout_3.addWidget(self.radioButtonModCHP, 1, 0, 1, 1)
        self.checkBoxFixCHP = QtGui.QCheckBox(self.tabCHP)
        self.checkBoxFixCHP.setObjectName("checkBoxFixCHP")
        self.gridLayout_3.addWidget(self.checkBoxFixCHP, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tabCHP, "")
        self.tabBoiler = QtGui.QWidget()
        self.tabBoiler.setObjectName("tabBoiler")
        self.gridLayout_4 = QtGui.QGridLayout(self.tabBoiler)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButtonAddBoiler = QtGui.QPushButton(self.tabBoiler)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddBoiler.sizePolicy().hasHeightForWidth())
        self.pushButtonAddBoiler.setSizePolicy(sizePolicy)
        self.pushButtonAddBoiler.setObjectName("pushButtonAddBoiler")
        self.gridLayout_4.addWidget(self.pushButtonAddBoiler, 1, 0, 1, 2)
        self.lineEditBoilerModelFix = QtGui.QLineEdit(self.tabBoiler)
        self.lineEditBoilerModelFix.setObjectName("lineEditBoilerModelFix")
        self.gridLayout_4.addWidget(self.lineEditBoilerModelFix, 3, 1, 1, 1)
        self.pushButtonAdvAnnuityBoiler = QtGui.QPushButton(self.tabBoiler)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdvAnnuityBoiler.sizePolicy().hasHeightForWidth())
        self.pushButtonAdvAnnuityBoiler.setSizePolicy(sizePolicy)
        self.pushButtonAdvAnnuityBoiler.setObjectName("pushButtonAdvAnnuityBoiler")
        self.gridLayout_4.addWidget(self.pushButtonAdvAnnuityBoiler, 0, 0, 1, 2)
        self.labelBoilerModelFix = QtGui.QLabel(self.tabBoiler)
        self.labelBoilerModelFix.setObjectName("labelBoilerModelFix")
        self.gridLayout_4.addWidget(self.labelBoilerModelFix, 3, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.tabBoiler)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_4.addWidget(self.checkBox, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabBoiler, "")
        self.tabThSt = QtGui.QWidget()
        self.tabThSt.setObjectName("tabThSt")
        self.gridLayout_5 = QtGui.QGridLayout(self.tabThSt)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButtonAdvAnnuityThSt = QtGui.QPushButton(self.tabThSt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdvAnnuityThSt.sizePolicy().hasHeightForWidth())
        self.pushButtonAdvAnnuityThSt.setSizePolicy(sizePolicy)
        self.pushButtonAdvAnnuityThSt.setObjectName("pushButtonAdvAnnuityThSt")
        self.gridLayout_5.addWidget(self.pushButtonAdvAnnuityThSt, 0, 0, 1, 2)
        self.pushButtonAddThSt = QtGui.QPushButton(self.tabThSt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddThSt.sizePolicy().hasHeightForWidth())
        self.pushButtonAddThSt.setSizePolicy(sizePolicy)
        self.pushButtonAddThSt.setObjectName("pushButtonAddThSt")
        self.gridLayout_5.addWidget(self.pushButtonAddThSt, 1, 0, 1, 2)
        self.checkBoxFixThSt = QtGui.QCheckBox(self.tabThSt)
        self.checkBoxFixThSt.setObjectName("checkBoxFixThSt")
        self.gridLayout_5.addWidget(self.checkBoxFixThSt, 2, 0, 1, 2)
        self.labelThStModelFix = QtGui.QLabel(self.tabThSt)
        self.labelThStModelFix.setObjectName("labelThStModelFix")
        self.gridLayout_5.addWidget(self.labelThStModelFix, 3, 0, 1, 1)
        self.lineEditThStModelFix = QtGui.QLineEdit(self.tabThSt)
        self.lineEditThStModelFix.setObjectName("lineEditThStModelFix")
        self.gridLayout_5.addWidget(self.lineEditThStModelFix, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tabThSt, "")
        self.tabSolTh = QtGui.QWidget()
        self.tabSolTh.setObjectName("tabSolTh")
        self.gridLayout_6 = QtGui.QGridLayout(self.tabSolTh)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButtonAddSolTh = QtGui.QPushButton(self.tabSolTh)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddSolTh.sizePolicy().hasHeightForWidth())
        self.pushButtonAddSolTh.setSizePolicy(sizePolicy)
        self.pushButtonAddSolTh.setObjectName("pushButtonAddSolTh")
        self.gridLayout_6.addWidget(self.pushButtonAddSolTh, 1, 0, 1, 2)
        self.pushButtonAdvAnnuitySolTh = QtGui.QPushButton(self.tabSolTh)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdvAnnuitySolTh.sizePolicy().hasHeightForWidth())
        self.pushButtonAdvAnnuitySolTh.setSizePolicy(sizePolicy)
        self.pushButtonAdvAnnuitySolTh.setObjectName("pushButtonAdvAnnuitySolTh")
        self.gridLayout_6.addWidget(self.pushButtonAdvAnnuitySolTh, 0, 0, 1, 2)
        self.labelSolThArea = QtGui.QLabel(self.tabSolTh)
        self.labelSolThArea.setObjectName("labelSolThArea")
        self.gridLayout_6.addWidget(self.labelSolThArea, 2, 0, 1, 1)
        self.lineEditSolThModelFix = QtGui.QLineEdit(self.tabSolTh)
        self.lineEditSolThModelFix.setObjectName("lineEditSolThModelFix")
        self.gridLayout_6.addWidget(self.lineEditSolThModelFix, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tabSolTh, "")
        self.tabElHe = QtGui.QWidget()
        self.tabElHe.setObjectName("tabElHe")
        self.gridLayout_7 = QtGui.QGridLayout(self.tabElHe)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButtonAdvAnnuityElHe = QtGui.QPushButton(self.tabElHe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdvAnnuityElHe.sizePolicy().hasHeightForWidth())
        self.pushButtonAdvAnnuityElHe.setSizePolicy(sizePolicy)
        self.pushButtonAdvAnnuityElHe.setObjectName("pushButtonAdvAnnuityElHe")
        self.gridLayout_7.addWidget(self.pushButtonAdvAnnuityElHe, 0, 0, 1, 2)
        self.pushButtonAddElHe = QtGui.QPushButton(self.tabElHe)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddElHe.sizePolicy().hasHeightForWidth())
        self.pushButtonAddElHe.setSizePolicy(sizePolicy)
        self.pushButtonAddElHe.setObjectName("pushButtonAddElHe")
        self.gridLayout_7.addWidget(self.pushButtonAddElHe, 1, 0, 1, 2)
        self.checkBoxFixElHe = QtGui.QCheckBox(self.tabElHe)
        self.checkBoxFixElHe.setObjectName("checkBoxFixElHe")
        self.gridLayout_7.addWidget(self.checkBoxFixElHe, 2, 0, 1, 1)
        self.labelElHeModelFix = QtGui.QLabel(self.tabElHe)
        self.labelElHeModelFix.setObjectName("labelElHeModelFix")
        self.gridLayout_7.addWidget(self.labelElHeModelFix, 3, 0, 1, 1)
        self.lineEditElHeModelFix = QtGui.QLineEdit(self.tabElHe)
        self.lineEditElHeModelFix.setObjectName("lineEditElHeModelFix")
        self.gridLayout_7.addWidget(self.lineEditElHeModelFix, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tabElHe, "")
        self.tabPV = QtGui.QWidget()
        self.tabPV.setObjectName("tabPV")
        self.gridLayout_8 = QtGui.QGridLayout(self.tabPV)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButtonAddPV = QtGui.QPushButton(self.tabPV)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddPV.sizePolicy().hasHeightForWidth())
        self.pushButtonAddPV.setSizePolicy(sizePolicy)
        self.pushButtonAddPV.setObjectName("pushButtonAddPV")
        self.gridLayout_8.addWidget(self.pushButtonAddPV, 1, 0, 1, 2)
        self.pushButtonAdvAnnuityPV = QtGui.QPushButton(self.tabPV)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdvAnnuityPV.sizePolicy().hasHeightForWidth())
        self.pushButtonAdvAnnuityPV.setSizePolicy(sizePolicy)
        self.pushButtonAdvAnnuityPV.setObjectName("pushButtonAdvAnnuityPV")
        self.gridLayout_8.addWidget(self.pushButtonAdvAnnuityPV, 0, 0, 1, 2)
        self.lineEditPVModelFix = QtGui.QLineEdit(self.tabPV)
        self.lineEditPVModelFix.setObjectName("lineEditPVModelFix")
        self.gridLayout_8.addWidget(self.lineEditPVModelFix, 2, 1, 1, 1)
        self.labelPVArea = QtGui.QLabel(self.tabPV)
        self.labelPVArea.setObjectName("labelPVArea")
        self.gridLayout_8.addWidget(self.labelPVArea, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabPV, "")
        self.tabElSt = QtGui.QWidget()
        self.tabElSt.setObjectName("tabElSt")
        self.gridLayout_9 = QtGui.QGridLayout(self.tabElSt)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButtonAdvAnnuityElSt = QtGui.QPushButton(self.tabElSt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdvAnnuityElSt.sizePolicy().hasHeightForWidth())
        self.pushButtonAdvAnnuityElSt.setSizePolicy(sizePolicy)
        self.pushButtonAdvAnnuityElSt.setObjectName("pushButtonAdvAnnuityElSt")
        self.gridLayout_9.addWidget(self.pushButtonAdvAnnuityElSt, 0, 0, 1, 2)
        self.pushButtonAddElSt = QtGui.QPushButton(self.tabElSt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAddElSt.sizePolicy().hasHeightForWidth())
        self.pushButtonAddElSt.setSizePolicy(sizePolicy)
        self.pushButtonAddElSt.setObjectName("pushButtonAddElSt")
        self.gridLayout_9.addWidget(self.pushButtonAddElSt, 1, 0, 1, 2)
        self.checkBoxFixElSt = QtGui.QCheckBox(self.tabElSt)
        self.checkBoxFixElSt.setObjectName("checkBoxFixElSt")
        self.gridLayout_9.addWidget(self.checkBoxFixElSt, 2, 0, 1, 1)
        self.labelElStModelFix = QtGui.QLabel(self.tabElSt)
        self.labelElStModelFix.setObjectName("labelElStModelFix")
        self.gridLayout_9.addWidget(self.labelElStModelFix, 3, 0, 1, 1)
        self.lineEditElStModelFix = QtGui.QLineEdit(self.tabElSt)
        self.lineEditElStModelFix.setObjectName("lineEditElStModelFix")
        self.gridLayout_9.addWidget(self.lineEditElStModelFix, 3, 1, 1, 1)
        self.tabWidget.addTab(self.tabElSt, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(60, 350, 156, 23))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 914, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        for index in range(3, 10):
            self.tabWidget.setTabEnabled(index, False)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)

        # QtCore.QObject.connect(self.check_box_chp, QtCore.SIGNAL("clicked(bool)"), self.check_box_chp.setChecked)
        # QtCore.QObject.connect(self.check_box_boiler, QtCore.SIGNAL("clicked(bool)"), self.check_box_boiler.setChecked)
        # QtCore.QObject.connect(self.check_box_elhe, QtCore.SIGNAL("clicked(bool)"), self.check_box_elhe.setChecked)
        # QtCore.QObject.connect(self.check_box_elst, QtCore.SIGNAL("clicked(bool)"), self.check_box_elst.setChecked)
        # QtCore.QObject.connect(self.check_box_pv, QtCore.SIGNAL("clicked(bool)"), self.check_box_pv.setChecked)
        # QtCore.QObject.connect(self.check_box_solth, QtCore.SIGNAL("clicked(bool)"), self.check_box_solth.setChecked)
        # QtCore.QObject.connect(self.check_box_thst, QtCore.SIGNAL("clicked(bool)"), self.check_box_thst.setChecked)
        # QtCore.QObject.connect(self.rbtn_hourly_excels, QtCore.SIGNAL("clicked(bool)"), self.rbtn_hourly_excels.setChecked)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Welcome to the SGT UI", None, QtGui.QApplication.UnicodeUTF8))
        self.label1.setText(QtGui.QApplication.translate("MainWindow", "Choose technologies that can be present in the system:", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_chp.setText(QtGui.QApplication.translate("MainWindow", "CHP", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_boiler.setText(QtGui.QApplication.translate("MainWindow", "Boiler", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_thst.setText(QtGui.QApplication.translate("MainWindow", "Thermal Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_solth.setText(QtGui.QApplication.translate("MainWindow", "Solar Thermal", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_elhe.setText(QtGui.QApplication.translate("MainWindow", "Electric Heater", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_pv.setText(QtGui.QApplication.translate("MainWindow", "Photovoltaics", None, QtGui.QApplication.UnicodeUTF8))
        self.check_box_elst.setText(QtGui.QApplication.translate("MainWindow", "Electric Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTechnologies), QtGui.QApplication.translate("MainWindow", "Technologies", None, QtGui.QApplication.UnicodeUTF8))
        self.OutputFolderLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Choose Output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOutputBrowse.setText(QtGui.QApplication.translate("MainWindow", "Browse..", None, QtGui.QApplication.UnicodeUTF8))
        self.WeatherDataLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Choose TRY weather file", None, QtGui.QApplication.UnicodeUTF8))
        self.btnWeathreBrowse.setText(QtGui.QApplication.translate("MainWindow", "Browse..", None, QtGui.QApplication.UnicodeUTF8))
        self.ElProfileLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Choose electrical profile", None, QtGui.QApplication.UnicodeUTF8))
        self.btnHeatprofilesBrowse.setText(QtGui.QApplication.translate("MainWindow", "Browse..", None, QtGui.QApplication.UnicodeUTF8))
        self.HProfileLineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Choose heat profile", None, QtGui.QApplication.UnicodeUTF8))
        self.btnElProfileBrowse.setText(QtGui.QApplication.translate("MainWindow", "Browse..", None, QtGui.QApplication.UnicodeUTF8))
        self.rbtn_hourly_excels.setText(QtGui.QApplication.translate("MainWindow", "Hourly excels required?", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFolders), QtGui.QApplication.translate("MainWindow", "Source and destination Folders", None, QtGui.QApplication.UnicodeUTF8))
        self.labelElPrice.setText(QtGui.QApplication.translate("MainWindow", "Electricity price", None, QtGui.QApplication.UnicodeUTF8))
        self.labelElPriceUnit.setText(QtGui.QApplication.translate("MainWindow", "[cents/kWh]", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGprice.setText(QtGui.QApplication.translate("MainWindow", "Gas price", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGPriceUnit.setText(QtGui.QApplication.translate("MainWindow", "[cents/kWh]", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGDetails), QtGui.QApplication.translate("MainWindow", "General Details", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCHPModelFix.setText(QtGui.QApplication.translate("MainWindow", "Choose Model", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddCHP.setText(QtGui.QApplication.translate("MainWindow", "Add/Modify Models in database", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAdvAnnuityCHP.setText(QtGui.QApplication.translate("MainWindow", "Modify Annuity Factors", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonContCHP.setText(QtGui.QApplication.translate("MainWindow", "Continuous CHP", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonONOFFCHP.setText(QtGui.QApplication.translate("MainWindow", "ON/OFF CHP", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCHPFIT.setText(QtGui.QApplication.translate("MainWindow", "CHP FIT in Euro Cents", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCHPFITUnit.setText(QtGui.QApplication.translate("MainWindow", "[cents/kWh]", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonModCHP.setText(QtGui.QApplication.translate("MainWindow", "Modulating CHP", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxFixCHP.setText(QtGui.QApplication.translate("MainWindow", "Fix CHP model", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCHP), QtGui.QApplication.translate("MainWindow", "CHP", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddBoiler.setText(QtGui.QApplication.translate("MainWindow", "Add/Modify Models in database", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAdvAnnuityBoiler.setText(QtGui.QApplication.translate("MainWindow", "Modify Annuity Factors", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBoilerModelFix.setText(QtGui.QApplication.translate("MainWindow", "Choose Model", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Fix Boiler model", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBoiler), QtGui.QApplication.translate("MainWindow", "Boiler", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAdvAnnuityThSt.setText(QtGui.QApplication.translate("MainWindow", "Modify Annuity Factors", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddThSt.setText(QtGui.QApplication.translate("MainWindow", "Add/Modify Models in database", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxFixThSt.setText(QtGui.QApplication.translate("MainWindow", "Fix Thermal Storage model", None, QtGui.QApplication.UnicodeUTF8))
        self.labelThStModelFix.setText(QtGui.QApplication.translate("MainWindow", "Choose Model", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabThSt), QtGui.QApplication.translate("MainWindow", "Thermal Storage", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddSolTh.setText(QtGui.QApplication.translate("MainWindow", "Add/Modify Models in database", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAdvAnnuitySolTh.setText(QtGui.QApplication.translate("MainWindow", "Modify Annuity Factors", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSolThArea.setText(QtGui.QApplication.translate("MainWindow", "Area", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSolTh), QtGui.QApplication.translate("MainWindow", "Solar Thermal", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAdvAnnuityElHe.setText(QtGui.QApplication.translate("MainWindow", "Modify Annuity Factors", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddElHe.setText(QtGui.QApplication.translate("MainWindow", "Add/Modify Models in database", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxFixElHe.setText(QtGui.QApplication.translate("MainWindow", "Fix Electric Heater model", None, QtGui.QApplication.UnicodeUTF8))
        self.labelElHeModelFix.setText(QtGui.QApplication.translate("MainWindow", "Choose Model", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabElHe), QtGui.QApplication.translate("MainWindow", "Electric Heater", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddPV.setText(QtGui.QApplication.translate("MainWindow", "Add/Modify Models in database", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAdvAnnuityPV.setText(QtGui.QApplication.translate("MainWindow", "Modify Annuity Factors", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPVArea.setText(QtGui.QApplication.translate("MainWindow", "PV Area", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPV), QtGui.QApplication.translate("MainWindow", "PV", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAdvAnnuityElSt.setText(QtGui.QApplication.translate("MainWindow", "Modify Annuity Factors", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddElSt.setText(QtGui.QApplication.translate("MainWindow", "Add/Modify Models in database", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxFixElSt.setText(QtGui.QApplication.translate("MainWindow", "Fix Electric Storage model", None, QtGui.QApplication.UnicodeUTF8))
        self.labelElStModelFix.setText(QtGui.QApplication.translate("MainWindow", "Choose Model", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabElSt), QtGui.QApplication.translate("MainWindow", "Electric Storage", None, QtGui.QApplication.UnicodeUTF8))

